"""criação inicial

Revision ID: 9672dec57643
Revises: 
Create Date: 2025-06-04 21:31:05.614440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9672dec57643'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_tag_tag_id_fkey'), 'post_tag', type_='foreignkey')
    op.drop_constraint(op.f('post_tag_post_id_fkey'), 'post_tag', type_='foreignkey')
    op.create_foreign_key(None, 'post_tag', 'posts', ['post_id'], ['_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_tag', 'tags', ['tag_id'], ['_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.create_foreign_key(op.f('post_tag_post_id_fkey'), 'post_tag', 'posts', ['post_id'], ['_id'])
    op.create_foreign_key(op.f('post_tag_tag_id_fkey'), 'post_tag', 'tags', ['tag_id'], ['_id'])
    # ### end Alembic commands ###
