import os

class Config:
	SECRET_KEY = os.getenv('SECRET_KEY')
	SESSION_COOKIE_SAMESITE = 'Lax'
	SESSION_TYPE = 'filesystem'
	SESSION_PERMANENT = False
	PERMANENT_SESSION_LIFETIME = 3600
	SESSION_FILE_THRESHOLD = 15
	SESSION_COOKIE_HTTPONLY = False
	SESSION_COOKIE_SECURE = False
	SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
	SQLALCHEMY_TRACK_MODIFICATIONS = False
