import os

class Config:
	SECRET_KEY = os.getenv('SECRET_KEY')
	SESSION_COOKIE_HTTPONLY = os.getenv('SESSION_COOKIE_HTTPONLY')
	SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE')
	SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE')
	SESSION_TYPE = 'filesystem'
	SESSION_FILE_THRESHOLD = 10
	SESSION_PERMANENT = True
	PERMANENT_SESSION_LIFETIME = 3600
	SESSION_FILE_THRESHOLD = 15
	

	# Database configuration
	SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
	SQLALCHEMY_TRACK_MODIFICATIONS = False
	DEBUG = os.getenv('DEBUG')
