import os

class Config:
	SECRET_KEY = os.getenv('SECRET_KEY')
	SESSION_COOKIE_HTTPONLY = os.getenv('CONFIG_SESSION_COOKIE_HTTPONLY', 'True') == 'True'
	SESSION_COOKIE_SECURE = os.getenv('CONFIG_SESSION_COOKIE_SECURE', 'True') == 'True'
	SESSION_COOKIE_SAMESITE = os.getenv('CONFIG_SESSION_COOKIE_SAMESITE')
	SESSION_TYPE = 'filesystem'
	SESSION_PERMANENT = False
	PERMANENT_SESSION_LIFETIME = 3600
	SESSION_COOKIE_HTTPONLY = False
	SESSION_COOKIE_SECURE = False
	SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
	SQLALCHEMY_TRACK_MODIFICATIONS = False
